-- 물고기 이름, 잡은 수
-- 물고기 종류 별로
-- 잡은 수 기준으로 내림차순 정렬
SELECT COUNT(N.FISH_TYPE) AS FISH_COUNT, N.FISH_NAME
FROM FISH_NAME_INFO AS N
JOIN FISH_INFO AS I ON N.FISH_TYPE = I.FISH_TYPE
GROUP BY N.FISH_TYPE, N.FISH_NAME
ORDER BY FISH_COUNT DESC;