WITH RECURSIVE GENERATIONS AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM GENERATIONS G
    JOIN ECOLI_DATA E
    ON E.PARENT_ID = G.ID 
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GENERATIONS
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID
                 FROM GENERATIONS
                 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION 